package enterprise.glassjoke.thirsty;

import enterprise.glassjoke.entity.OfficeEntity;

/**
 * A thirsty factor is anything that can make an office entity thirsty.
 *
 * Current implementation has only two factors: room temperature and work intensity. More factors might be added in the
 * future.
 *
 * @author hkotsubo
 */
public interface ThirstyFactor {

    /**
     * Get the thirsty level generated by that this factor
     *
     * @param entity The office entity affected by this factor
     *
     * @return The amount of milliliters the entity wants to drink
     */
    public int getThirstyLevel(OfficeEntity entity);
}
